/**
 * Classes generated by the Android Studio master-detail activity wizard, and then modified for
 * the Northwind application.
 *
 * @see com.incture.mobility.metrodata
 */
package com.incture.mobility.metrodata.views;